MM-47904 Add tests for nps data job
mattermost/mattermost-data-warehouse pull request #1045
Opened 2022-11-09 14:42 UTC by munish7771

#### Summary

- [x] Updated structure of post_nps_data.py to avoid reloading the module.
- [x] Added tests configuration
- [x] Added unit tests

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-47903

2022-11-09 15:54 UTC, ifoukarakis requested changes
Thanks for the PR! Left some suggestions for improvements.

2022-11-09 15:54 UTC, ifoukarakis commented on tests/utils/test_post_nps_data.py
> +
```suggestion
```
No reason to keep the empty lines at the end of the file.

2022-11-09 15:54 UTC, ifoukarakis commented on tests/utils/test_post_nps_data.py
> +    def test_snowflake_connection(self, config_nps, responses, post_nps_ok, mock_snowflake_connector):
Not sure if we need this test case. It can be merged with the next test case.

2022-11-09 15:54 UTC, ifoukarakis commented on tests/utils/test_post_nps_data.py
> +        assert os.getenv("NPS_WEBHOOK_URL") == "https://mattermost.example.com/hooks/hookid"
Since this is set in a fixture, there's no reason to test it.

2022-11-09 15:54 UTC, ifoukarakis commented on tests/utils/test_post_nps_data.py
> +        responses.assert_call_count("https://mattermost.example.com/hooks/hookid", 1)
This is great. A more detailed test would check the payload that was sent to this endpoint.

2022-11-09 15:54 UTC, ifoukarakis commented on tests/utils/test_post_nps_data.py
> +        try:
pytest allows to check for [expected exceptions](https://docs.pytest.org/en/7.1.x/how-to/assert.html#assertions-about-expected-exceptions).

2022-11-17 14:59 UTC, munish7771 commented
@ifoukarakis I have made the review changes, can you review and approve?

2022-11-17 15:11 UTC, ifoukarakis approved these changes

2022-11-17 15:14 UTC, merged