MM-50992 Fix looker error with dashboard FocalBoard Analytics
mattermost/mattermost-data-warehouse pull request #1193
Opened 2023-03-06 03:57 UTC by sri-byte

Impact: Fix looker error with dashboard FocalBoard Analytics.

#### Summary

#### Ticket Link

2023-03-06 14:30 UTC, catalintomai approved these changes

2023-03-06 15:08 UTC, munish7771 commented on transform/snowflake-dbt/models/mattermost/hourly/focalboard_user_retention.sql
> +FROM q2 q2
dont need alias q2

2023-03-06 15:18 UTC, munish7771 commented on transform/snowflake-dbt/models/mattermost/hourly/focalboard_user_retention.sql
> +) SELECT DISTINCT
can we use a dbt formatter?
)
SELECT
  DISTINCT q2.first_active_timestamp,
  q2.server_id,
  q2.user_id,
  q2.installation_id,
  q2.first_server_edition,
  q2.id,
  q2.age,
  q2.max_original_timestamp,
  fet3.type AS TYPE
FROM
  q2 q2
  LEFT JOIN {{ ref('focalboard_event_telemetry') }}
  fet3
  ON fet3.user_actual_id = q2.user_id

2023-03-06 15:20 UTC, catalintomai commented
Is there a Jira ticket this corresponds to? If yes, please include in the description. Thanks.

2023-03-06 15:20 UTC, munish7771 requested changes
@ifoukarakis do we have a formatter for dbt ?
I use this in VS code-> https://marketplace.visualstudio.com/items?itemName=henriblancke.vscode-dbt-formatter

2023-03-06 19:04 UTC, ifoukarakis commented
> @ifoukarakis do we have a formatter for dbt ? I use this in VS code-> https://marketplace.visualstudio.com/items?itemName=henriblancke.vscode-dbt-formatter

sqlfluff is a linter works with dbt, but requires [configuration](https://docs.sqlfluff.com/en/stable/configuration.html#dbt-project-configuration).

IMHO relying on IDE specific formatter is challenging. The main shortcomings are:
- Every team member will need to either use the same IDE/configuration or find plugins supported by all IDEs the team is using and make sure they are configured in the same way.
- Requires a manual step for formatting that each developer will need to remember (unless the IDE auto-formats your code).

2023-04-13 14:27 UTC, munish7771 approved these changes

2023-04-13 22:52 UTC, merged