MM-51859 Updated models to prioritize cloud_dns for domain name
mattermost/mattermost-data-warehouse pull request #1269
Opened 2023-05-03 00:26 UTC by sri-byte

Impact: This PR updates the cloud models to use cloud_dns as the first source for domain, before gmail.com.

https://mattermost.atlassian.net/browse/MM-51859

#### Summary

#### Ticket Link

2023-05-03 08:38 UTC, munish7771 reviewed
are we also doing a backfill while deploying?

2023-05-04 09:25 UTC, catalintomai commented
Based on yadav's comments, do we need to update `customers_with_onprem_subs.sql` model? (until we push the new model)? - need to also update the new one as well I believe.

2023-05-04 11:49 UTC, ifoukarakis requested changes
There's a couple of changes needed:
- The SQL queries will not run.
- No need to replace domain with first part of cloud dns. It just doesn't add any value.
- After testing the changes I noticed that there's a single account that most gmail accounts have been mapped to.

2023-05-05 15:38 UTC, sri-byte commented on transform/snowflake-dbt/models/blapi/customers_with_cloud_free_subs.sql
> +        ELSE SPLIT_PART(customers.email, '@', 2) as domain,
Fixed now.

2023-05-05 17:27 UTC, ifoukarakis requested changes

2023-05-05 17:27 UTC, ifoukarakis commented on transform/snowflake-dbt/models/blapi/customers_with_freemium_subs.sql
> +        COALESCE(SPLIT_PART(cloud_subscriptions.cloud_dns, '.', 1), SPLIT_PART(customers.email, '@', 2)) as domain,
Let's use the same logic as in the other models here as well.

2023-05-08 06:17 UTC, ifoukarakis approved these changes

2023-05-08 11:14 UTC, catalintomai approved these changes

2023-05-08 14:58 UTC, merged