MM-57112 Add new sources to push proxy server logs
mattermost/mattermost-data-warehouse pull request #1470
Opened 2024-03-27 10:02 UTC by sri-byte

#### Summary

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-57112

2024-03-27 16:46 UTC, catalintomai commented on transform/mattermost-analytics/models/staging/push_proxy/_push_proxy__sources.yml
> +        description: Logs from test notification server.
why 'test'?

2024-03-27 16:46 UTC, catalintomai commented on transform/mattermost-analytics/models/staging/push_proxy/_push_proxy__sources.yml
> +        description: Logs from test notification server.
why 'test'?

2024-03-28 08:41 UTC, sri-byte commented on transform/mattermost-analytics/models/staging/push_proxy/_push_proxy__sources.yml
> +        description: Logs from test notification server.
Updated, was a copy paste oversight.

2024-03-28 08:41 UTC, sri-byte commented on transform/mattermost-analytics/models/staging/push_proxy/_push_proxy__sources.yml
> +        description: Logs from test notification server.
updated

2024-04-01 09:26 UTC, ifoukarakis requested changes
Value addition must handle nulls.

Some small issues in docs as well.

2024-04-01 10:34 UTC, sri-byte commented on transform/mattermost-analytics/models/marts/product/notifications/fct_notification_stats.sql
> +    coalesce(eu_logs.count_send_push + logs_eu.count_send_push, 0) as count_eu_send_push,
Updated, used `dbt_utils.safe_add`.

2024-04-01 10:35 UTC, sri-byte commented on transform/mattermost-analytics/models/staging/push_proxy/_push_proxy__sources.yml
> +          - name: classification_reason
Added descriptions.

2024-04-01 10:42 UTC, ifoukarakis reviewed
The `test` mentions persist. Same for missing docs.

2024-04-01 10:50 UTC, sri-byte commented
Thanks @ifoukarakis, I missed updating the staging model.yml, had to update the descriptions in 2 places.

2024-04-01 10:58 UTC, ifoukarakis approved these changes

2024-04-01 11:02 UTC, merged