Breaking CTE's in license_server_fact to their own individual tables.
mattermost/mattermost-data-warehouse pull request #882
Opened 2022-01-19 00:49 UTC by sri-byte

The data in license_server_fact remains the same. The CTE's have their own individual tables with this commit and license_server_fact references those tables, due to which there is no impact on license_server_fact.

This improves readability as well as helps us find and debug any data issues, and improves data quality and improves run time.

#### Summary

#### Ticket Link

2022-01-19 01:17 UTC, nickmisasi requested changes
Great work @sri-byte! One thing to address

2022-01-19 01:17 UTC, nickmisasi commented on transform/snowflake-dbt/models/blp/licensed_servers.sql
> +AND l.license_id <> 'xmfoy61ru3r55kcosr9bpyw35h'
I think you can remove these 2 conditions. I put them there and they're not needed. `16tfkttgktgdmb5m8xakqncx3c` is from before my time, so not sure what it's for. Maybe we can remove that too and see what happens?

2022-01-19 01:32 UTC, jasonblais commented
@sri-byte Thank you! 

Propose adding these two notes into the PR description, as a best practice:

1. Do we see any risks or side effects this change may introduce?
2. Did we complete testing / verification of this change?

2022-01-21 18:13 UTC, sri-byte commented
@jasonblais 

1. The dbt materialization settings for the 3 new tables I set intially to 'Incremental', this will not work as we have the ID column which is being created as a combination of server_id and license_id, and in the data we have duplicates. This was identified and fixed by changing the setting to 'table'
2. The changes have been fully tested locally and in production.

2022-01-21 18:30 UTC, nickmisasi approved these changes

2022-01-24 20:24 UTC, jasonblais commented
@sri-byte thanks! Can you help include the above two notes in your future PR descriptions :+1:

2022-01-26 18:49 UTC, merged

2022-01-28 00:15 UTC, sri-byte commented on transform/snowflake-dbt/models/blp/license_server_fact.sql
> -    {{ dbt_utils.surrogate_key(['l.license_id', 'l.server_id']) }} as id
We don't need to add account_mapping since the unique ID is being generated in licensed_servers and nonactivated_licenses. @jasonblais